---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "github-actions-runner.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "github-actions-runner.serviceAccountName" . }}
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: {{ include "github-actions-runner.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
