apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "github-actions-runner.fullname" . }}
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
data:
  ghr_pat_token: "{{ .Values.runner.ghr_pat_token | b64enc }}"
