apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "<CHARTNAME>.fullname" . }}
spec:
  hosts:
    - hostname
  gateways:
    - istio-system/https-gateway
  http:
    - name: rest
      match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: {{ .Values.service.port }}
            host: {{ include "<CHARTNAME>.fullname" . }}
