
build tag="latest":
    docker build -t 903369196314.dkr.ecr.us-east-1.amazonaws.com/github-action-runner .

push tag="latest":
    docker push 903369196314.dkr.ecr.us-east-1.amazonaws.com/github-action-runner

regcred:
    kubectl create secret docker-registry regcred \
      --docker-server=903369196314.dkr.ecr.us-east-1.amazonaws.com \
      --docker-username=AWS \
      --docker-password=$(aws ecr --region us-east-1 get-login-password) \
      --namespace=github

install:
    helm upgrade --install ghr . --set "runner.ghr_pat_token=$(cat ~/.github/token)"

ecr-login:
    aws ecr \
      get-login-password \
      --region us-east-1 | docker login \
      --username AWS \
      --password-stdin \
      903369196314.dkr.ecr.us-east-1.amazonaws.com

