{{- if .Values.alertmanager.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "<CHARTNAME>.name" . }}-slack-webhook
data:
  webhookURL: "{{ .Values.slack_webhook_url }}"
{{- end }}
