---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}
spec:
  endpoints:
    - interval: 30s
      port: metrics
      path: /metrics
      scheme: https
      tlsConfig:
        caFile: /etc/istio-certs/root-cert.pem
        certFile: /etc/istio-certs/cert-chain.pem
        insecureSkipVerify: true
        keyFile: /etc/istio-certs/key.pem
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "test.labels" . | nindent 6 }}
