name: Helm build cloud-services charts

# bkroger012

on:
  push:
    paths:
      - ".github/workflows/test-helm.yaml"
      - ".github/workflows/build-helm.yaml"
      - ".github/actions/**"
      - "charts/app-backend/**"

permissions:
  issues: write
  checks: write
  contents: read
  id-token: write
  pull-requests: write

jobs:
  test-basic-application:
    uses: krogebry/workflows/.github/workflows/build-helm.yaml@cicd-test
    with:
      publish: false
      helm_repo_name: krogebry
      helm_chart_path: charts/app-backend
      helm_chart_test_path: test/no_values
      helm_chart_name: app-be-no-values
      helm_values_path: .deploy/no_values
    secrets:
      git_ssh_key: ${{ secrets.GIT_SSH_KEY }}
      sg_github_token: ${{ secrets.SG_GITHUB_LEGACY_TOKEN }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
